//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuthenticationService
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://lorillard.com/AuthenticationService", ConfigurationName="ServiceReference1.AuthenticationSoap")]
    public interface AuthenticationSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://lorillard.com/AuthenticationService/GetSiteMinder", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<AuthenticationService.SiteMinderResponse> GetSiteMinderAsync(string userId, string password, string DeviceName, string UserName, string ApplicationName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://lorillard.com/AuthenticationService/ParseSiteMinder", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<AuthenticationService.ActiveResponse> ParseSiteMinderAsync(string siteMinderResponse, string DeviceName, string UserName, string ApplicationName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://lorillard.com/AuthenticationService/ParseSiteMinderForApplication", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<AuthenticationService.ActiveResponse> ParseSiteMinderForApplicationAsync(string siteMinderResponse, string application, string DeviceName, string UserName, string ApplicationName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://lorillard.com/AuthenticationService/ParseActiveResponseForApplication", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<AuthenticationService.ActiveResponse> ParseActiveResponseForApplicationAsync(AuthenticationService.SiteMinderResponse siteMinderResponse, string application, string DeviceName, string UserName, string ApplicationName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://lorillard.com/AuthenticationService/VerifyRole", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<bool> VerifyRoleAsync(string userId, string password, string role, string application, string DeviceName, string UserName, string ApplicationName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://lorillard.com/AuthenticationService/GetUserApplicationsPrivileges", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<AuthenticationService.UserPrivilege[]> GetUserApplicationsPrivilegesAsync(string userId, string application, string DeviceName, string UserName, string ApplicationName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://lorillard.com/AuthenticationService/GetUserApplicationsPrivilegesEx", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<AuthenticationService.UserPrivilegeEx[]> GetUserApplicationsPrivilegesExAsync(string userId, string application, string DeviceName, string UserName, string ApplicationName);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://lorillard.com/AuthenticationService")]
    public partial class SiteMinderResponse
    {
        
        private string userIdField;
        
        private string passwordField;
        
        private string cookieField;
        
        private bool errorOccurredField;
        
        private string errorDescriptionField;
        
        private string responseField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string UserId
        {
            get
            {
                return this.userIdField;
            }
            set
            {
                this.userIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Cookie
        {
            get
            {
                return this.cookieField;
            }
            set
            {
                this.cookieField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool ErrorOccurred
        {
            get
            {
                return this.errorOccurredField;
            }
            set
            {
                this.errorOccurredField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ErrorDescription
        {
            get
            {
                return this.errorDescriptionField;
            }
            set
            {
                this.errorDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Response
        {
            get
            {
                return this.responseField;
            }
            set
            {
                this.responseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://lorillard.com/AuthenticationService")]
    public partial class UserPrivilegeEx
    {
        
        private string dBUserField;
        
        private string dBPasswordField;
        
        private string applicationField;
        
        private string titleField;
        
        private string roleField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DBUser
        {
            get
            {
                return this.dBUserField;
            }
            set
            {
                this.dBUserField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DBPassword
        {
            get
            {
                return this.dBPasswordField;
            }
            set
            {
                this.dBPasswordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Application
        {
            get
            {
                return this.applicationField;
            }
            set
            {
                this.applicationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Title
        {
            get
            {
                return this.titleField;
            }
            set
            {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Role
        {
            get
            {
                return this.roleField;
            }
            set
            {
                this.roleField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://lorillard.com/AuthenticationService")]
    public partial class UserPrivilege
    {
        
        private string dBUserField;
        
        private string dBPasswordField;
        
        private string applicationField;
        
        private string roleField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string DBUser
        {
            get
            {
                return this.dBUserField;
            }
            set
            {
                this.dBUserField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string DBPassword
        {
            get
            {
                return this.dBPasswordField;
            }
            set
            {
                this.dBPasswordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Application
        {
            get
            {
                return this.applicationField;
            }
            set
            {
                this.applicationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Role
        {
            get
            {
                return this.roleField;
            }
            set
            {
                this.roleField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://lorillard.com/AuthenticationService")]
    public partial class AppInfo
    {
        
        private string idField;
        
        private string roleField;
        
        private string dbUserField;
        
        private string dbPasswordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ID
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Role
        {
            get
            {
                return this.roleField;
            }
            set
            {
                this.roleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string DbUser
        {
            get
            {
                return this.dbUserField;
            }
            set
            {
                this.dbUserField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string DbPassword
        {
            get
            {
                return this.dbPasswordField;
            }
            set
            {
                this.dbPasswordField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://lorillard.com/AuthenticationService")]
    public partial class ActiveResponse
    {
        
        private bool errorOccurredField;
        
        private string errorDescriptionField;
        
        private string dbNameField;
        
        private string dbServerField;
        
        private AppInfo[] applicationsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool ErrorOccurred
        {
            get
            {
                return this.errorOccurredField;
            }
            set
            {
                this.errorOccurredField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ErrorDescription
        {
            get
            {
                return this.errorDescriptionField;
            }
            set
            {
                this.errorDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string DbName
        {
            get
            {
                return this.dbNameField;
            }
            set
            {
                this.dbNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string DbServer
        {
            get
            {
                return this.dbServerField;
            }
            set
            {
                this.dbServerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=4)]
        public AppInfo[] Applications
        {
            get
            {
                return this.applicationsField;
            }
            set
            {
                this.applicationsField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface AuthenticationSoapChannel : AuthenticationService.AuthenticationSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class AuthenticationSoapClient : System.ServiceModel.ClientBase<AuthenticationService.AuthenticationSoap>, AuthenticationService.AuthenticationSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public AuthenticationSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(AuthenticationSoapClient.GetBindingForEndpoint(endpointConfiguration), AuthenticationSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AuthenticationSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(AuthenticationSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AuthenticationSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(AuthenticationSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AuthenticationSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<AuthenticationService.SiteMinderResponse> GetSiteMinderAsync(string userId, string password, string DeviceName, string UserName, string ApplicationName)
        {
            return base.Channel.GetSiteMinderAsync(userId, password, DeviceName, UserName, ApplicationName);
        }
        
        public System.Threading.Tasks.Task<AuthenticationService.ActiveResponse> ParseSiteMinderAsync(string siteMinderResponse, string DeviceName, string UserName, string ApplicationName)
        {
            return base.Channel.ParseSiteMinderAsync(siteMinderResponse, DeviceName, UserName, ApplicationName);
        }
        
        public System.Threading.Tasks.Task<AuthenticationService.ActiveResponse> ParseSiteMinderForApplicationAsync(string siteMinderResponse, string application, string DeviceName, string UserName, string ApplicationName)
        {
            return base.Channel.ParseSiteMinderForApplicationAsync(siteMinderResponse, application, DeviceName, UserName, ApplicationName);
        }
        
        public System.Threading.Tasks.Task<AuthenticationService.ActiveResponse> ParseActiveResponseForApplicationAsync(AuthenticationService.SiteMinderResponse siteMinderResponse, string application, string DeviceName, string UserName, string ApplicationName)
        {
            return base.Channel.ParseActiveResponseForApplicationAsync(siteMinderResponse, application, DeviceName, UserName, ApplicationName);
        }
        
        public System.Threading.Tasks.Task<bool> VerifyRoleAsync(string userId, string password, string role, string application, string DeviceName, string UserName, string ApplicationName)
        {
            return base.Channel.VerifyRoleAsync(userId, password, role, application, DeviceName, UserName, ApplicationName);
        }
        
        public System.Threading.Tasks.Task<AuthenticationService.UserPrivilege[]> GetUserApplicationsPrivilegesAsync(string userId, string application, string DeviceName, string UserName, string ApplicationName)
        {
            return base.Channel.GetUserApplicationsPrivilegesAsync(userId, application, DeviceName, UserName, ApplicationName);
        }
        
        public System.Threading.Tasks.Task<AuthenticationService.UserPrivilegeEx[]> GetUserApplicationsPrivilegesExAsync(string userId, string application, string DeviceName, string UserName, string ApplicationName)
        {
            return base.Channel.GetUserApplicationsPrivilegesExAsync(userId, application, DeviceName, UserName, ApplicationName);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.AuthenticationSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.AuthenticationSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.AuthenticationSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://ltrwebsvcqa.lco.lortobco.com/Authentication/Authentication.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.AuthenticationSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://ltrwebsvcqa.lco.lortobco.com/Authentication/Authentication.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            AuthenticationSoap,
            
            AuthenticationSoap12,
        }
    }
}
