//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIIService
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.sap.com/xMII", ConfigurationName="MIIService.XacuteWSSoap")]
    public interface XacuteWSSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.sap.com/xMII", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<MIIService.XacuteResponse> XacuteAsync(MIIService.XacuteRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.sap.com/xMII")]
    public partial class InputParams
    {
        
        private string xmlInputField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string XmlInput
        {
            get
            {
                return this.xmlInputField;
            }
            set
            {
                this.xmlInputField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.sap.com/xMII")]
    public partial class Row
    {
        
        private string xmlOutputField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string XmlOutput
        {
            get
            {
                return this.xmlOutputField;
            }
            set
            {
                this.xmlOutputField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.sap.com/xMII")]
    public partial class Rowset
    {
        
        private Row[] rowField;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Row", Order=0)]
        public Row[] Row
        {
            get
            {
                return this.rowField;
            }
            set
            {
                this.rowField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="XacuteRequest", WrapperNamespace="http://www.sap.com/xMII", IsWrapped=true)]
    public partial class XacuteRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.sap.com/xMII", Order=0)]
        public string LoginName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.sap.com/xMII", Order=1)]
        public string LoginPassword;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.sap.com/xMII", Order=2)]
        public MIIService.InputParams InputParams;
        
        public XacuteRequest()
        {
        }
        
        public XacuteRequest(string LoginName, string LoginPassword, MIIService.InputParams InputParams)
        {
            this.LoginName = LoginName;
            this.LoginPassword = LoginPassword;
            this.InputParams = InputParams;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="XacuteResponse", WrapperNamespace="http://www.sap.com/xMII", IsWrapped=true)]
    public partial class XacuteResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.sap.com/xMII", Order=0)]
        public MIIService.Rowset Rowset;
        
        public XacuteResponse()
        {
        }
        
        public XacuteResponse(MIIService.Rowset Rowset)
        {
            this.Rowset = Rowset;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface XacuteWSSoapChannel : MIIService.XacuteWSSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class XacuteWSSoapClient : System.ServiceModel.ClientBase<MIIService.XacuteWSSoap>, MIIService.XacuteWSSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public XacuteWSSoapClient() : 
                base(XacuteWSSoapClient.GetDefaultBinding(), XacuteWSSoapClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.XacuteWSSoap.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public XacuteWSSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(XacuteWSSoapClient.GetBindingForEndpoint(endpointConfiguration), XacuteWSSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public XacuteWSSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(XacuteWSSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public XacuteWSSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(XacuteWSSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public XacuteWSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MIIService.XacuteResponse> MIIService.XacuteWSSoap.XacuteAsync(MIIService.XacuteRequest request)
        {
            return base.Channel.XacuteAsync(request);
        }
        
        public System.Threading.Tasks.Task<MIIService.XacuteResponse> XacuteAsync(string LoginName, string LoginPassword, MIIService.InputParams InputParams)
        {
            MIIService.XacuteRequest inValue = new MIIService.XacuteRequest();
            inValue.LoginName = LoginName;
            inValue.LoginPassword = LoginPassword;
            inValue.InputParams = InputParams;
            return ((MIIService.XacuteWSSoap)(this)).XacuteAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.XacuteWSSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.XacuteWSSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://infmiiqa.itgbrands.net:50100/XMII/SOAPRunner/LTRI/MSMQInboundRouting/Cutting/CuttingEntryRouter");
                     
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return XacuteWSSoapClient.GetBindingForEndpoint(EndpointConfiguration.XacuteWSSoap);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return XacuteWSSoapClient.GetEndpointAddress(EndpointConfiguration.XacuteWSSoap);
        }
        
        public enum EndpointConfiguration
        {
            
            XacuteWSSoap,
        }
    }
}
